components/ConversionPanel.js
yarn.lock

Hi @ritz078 ,
I'm proposing to add background color property to the success and error messages. E.g: `Code copied to clipboard.`
Here's the screens of the UI:

🎨 Style: Change style of the error and success messages.

---

components/ConversionPanel.js
components/Layout.js
pages/json-to-rust-serde.js
utils/json-to-rust-serde.js

Adds a transform from JSON to Rusts *ser*ialization/*de*serialization framework, saving a lot of boilerplaty work for another community :).
Thanks for this page :).

Add JSON to Rust Serde

---

pages/index.js
utils/babel-plugin-js-to-immutable-prop-types.js

So I decided to give it a go on this today itself because I got another idea to hack during the weekend 😆 
I'm still going through James awesome babel plugin handbook and this is my first plugin so the immutable plugin is a shameless copy of the JSON to prop-types plugin. So let me know if you notice any issues and would be happy to correct them.

Support for react-immutable-proptypes (#14)

---

package.json

While am at fixing #34 added bugs and author as well :slightly_smiling_face:

added repository, author and bugs filed in package.json

---

components/ConversionPanel.js
package.json
utils/worker.js
yarn.lock

moved prettier to worker

---

pages/xml-to-json.js

previously had JSON title for the XML and XML for the JSON

Swap titles on xml to json to correctly match whats rendered

---

.gitignore
pages/html-to-jsx.js
pages/svg-to-react-native.js
utils/routes.js

Fix #58
Hooray! If you want to change the titles or descriptions feel free to tell me!

Make SVG to JSX optimization optional & move React Native SVG to another page

---

components/ConversionPanel.tsx
components/Monaco.tsx
package.json
pages/css-to-js.tsx
pages/flow-to-typescript.tsx
pages/graphql-to-components.tsx
pages/graphql-to-flow.tsx
pages/graphql-to-fragment-matcher.tsx
pages/graphql-to-introspection-json.tsx
pages/graphql-to-java.tsx
pages/graphql-to-schema-ast.tsx
pages/graphql-to-typescript-mongodb.tsx
pages/graphql-to-typescript.tsx
pages/html-to-jsx.tsx
pages/index.tsx
pages/json-schema-to-typescript.tsx
pages/json-to-graphql.tsx
pages/json-to-mobx-state-tree.tsx
pages/svg-to-react-native.tsx
pages/xml-to-json.tsx
pages/yaml-to-json.tsx
utils/prettify.ts
utils/routes.tsx
yarn.lock

feat(graphql): added json to graphql transform

---

assets/vendor/json-to-jsdoc.js
pages/json-to-jsdoc.tsx
utils/routes.tsx

feat(jsdoc): added JSON to JSDoc transformation

---

components/Navigator.tsx
constants/data.ts
hooks/useSessionStorage.ts
package.json
pages/_app.tsx
pages/_document.tsx
yarn.lock

fix: producthunt, twitter url

---

pages/json-to-mysql.tsx

This also was likely due to copy-paste

fix title for MySQL

---

pages/json-to-big-query.tsx

probably a little forgotten to edit copy paste

fix title for bigQuery

---

pages/_app.tsx

fix(404): show 404 page

---

pages/json-to-go-bson.tsx
utils/routes.tsx

Can be used to transform JS queries to bson on Go

Add support for bson on Go

---

components/Navigator.tsx

fix: stop ad display in Dev mode

---

assets/vendor/json-to-jsdoc.js

Made use of `includes()` to check for existence.

chore: minor code refactoring

---

constants/data.ts
package.json
pages/css-to-tailwind.tsx
utils/routes.tsx
yarn.lock

~Work in progress~
~*I opened this PR here by accident, I wanted to open it in my fork. 😅*~
The PR is ready for review. I think this transformer at its current form can give good value to its users, however two main things are missing: [variants](https://tailwindcss.com/docs/configuration#variants) support, and support for custom Tailwind [configs](https://tailwindcss.com/docs/configuration).
- Variant support: I want to implement it properly, so I need some time to think on the problem.
- Config: The [css-to-tailwind](https://github.com/miklosme/css-to-tailwind) package does support any configs, but it requires to run PostCSS, and I need to figure out how to do that in this project properly.

CSS to TailwindCSS

---

package.json

Update posscss-js to v3.0.0

---

constants/data.ts
hooks/useLocalStorage.ts
package.json
pages/html-to-jsx.tsx
patches/htmltojsx+0.3.0.patch
utils/prettify.ts

Improvements in html to JSX transformer

---

patches/relay-compiler+10.0.1.patch

fix(gql-ts): fixes an issue where process.hrtime was not defined in worker

---

constants/data.ts
package.json
pages/json-to-toml.tsx
pages/toml-to-json.tsx
utils/routes.tsx
yarn.lock

add toml support:
- JSON to TOML (`/json-to-toml`)
- TOML to JSON (`/toml-to-json`)

add `json to toml` and `toml to json`

---

package.json
yarn.lock

Update TOML parser

---

package.json
pages/_app.tsx
yarn.lock

Revert "Ganalytics"

---

components/EditorPanel.tsx
components/Navigator.tsx
hooks/useDarkMode.ts
pages/_app.tsx
styles/main.css

- Adds a button to toggle light/dark mode
- Persists the value in local storage
> Demo
<p align="center"><img src="https://user-images.githubusercontent.com/92991945/213939887-02722d5d-b562-4640-9aa2-999729138e22.gif" width="700" /></p>

✨ Add dark mode

---

README.md

Adding @SuttonJack as a sponsor to the project.

Add Jack Sutton as sponsor

---

constants/data.ts
package.json
pages/cadence-to-go.tsx
utils/routes.tsx
yarn.lock

Now support whole contract interaction code generation!

Feat: new cadence to go transform backend

---

package.json
pages/css-to-tailwind.tsx
yarn.lock

Update "CSS to Tailwind" page

---

pages/js-object-to-typescript.tsx
utils/routes.tsx

- adds js object to typescript transformer by first converting the js object to JSON and then to typescript.

feat: add js object to typescript converter
